name = "Elly's MTR Quilt 1.19.2 pack"
author = "Octelly"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37309a79dff0480da5c8e9235ed1ab27753c56d880fbb00b5bb245664cb3ceac"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"

[options]

>>>>>>> c9c9b6c (Initial commit)
datapack-folder = "config/openloader/data"
