name = "Elly's MTR Quilt 1.19.2 pack"
author = "Octelly"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5414b3d4be182f6f9007ab65bc37d619bf6510e84b6299215393fae84ed1cbf9"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"

[options]
datapack-folder = "config/openloader/data"
