name = "Elly's MTR Quilt 1.19.2 pack"
author = "Octelly"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c184da11ee517bfa63ff95c806c3b602a77082420c9a4e2b34fd48971874c9c5"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"

[options]
datapack-folder = "config/openloader/data"
